[package]
name = "dns_drop"
version = "0.1.0"
authors = ["Mark Percival <m@mdp.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.4.0"
clap = "2.33.3"
regex = "1.4.4"
serde_json = "1.0"
chrono = "0.4"
