on: [push]

name: CI

jobs:
  build_and_test:
    defaults:
      run:
        working-directory: server
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo clippy
      - run: cargo build